name: python workflow
on:
  push:
jobs:
  job1:
   stratergy:
     matric: 
      python-version: [3.9,3.8]
   runs-on: ubuntu-latest
   steps: 
    - name: checkout code
      uses: action/heckout@v4
    - name: setup python 3.6
      uses: action/checkout@v5
      with: 
       python-version: ${{ matrix.python-version}}
    - name: install dependencies
      run: 
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: set pythonpath
      run: echo "PYTHONPATH"=$GITHUB_WORKSPACE >> $GITHUB_ENV
    - name: python link
      run: flake8 app.py tests/
    - name: Run tests/
      run: pytest tests --cov=app --cov-report=xml
